spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: cursoms-eureka-user
      password: reemaskrrs-oc-useuu
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
